export enum ExecutorKind {
  AGENT_EVALUATOR = "AGENT_EVALUATOR",
  AGENT_EXECUTOR = "AGENT_EXECUTOR",
  ASSET_PROCESSOR = "ASSET_PROCESSOR",
  AUTOMATION_EXECUTOR = "AUTOMATION_EXECUTOR",
  LEXICON_BUILDER = "LEXICON_BUILDER",
  LEXICON_PUBLISHER = "LEXICON_PUBLISHER",
}

export const EXECUTOR_KINDS: readonly ExecutorKind[] = Object.freeze(
  Object.values(ExecutorKind),
);
