export enum JobKind {
  AGENT_RELEASE_EVALUATION = "AGENT_RELEASE_EVALUATION",
  AGENT_RELEASE_JUDGEMENT = "AGENT_RELEASE_JUDGEMENT",
  AGENT_RUN_ACTIVATION = "AGENT_RUN_ACTIVATION",
  AGENT_TOOL_CONTINUATION = "AGENT_TOOL_CONTINUATION",
  ASSET_EMBEDDING = "ASSET_EMBEDDING",
  ASSET_EXTRACT = "ASSET_EXTRACT",
  ASSET_IMAGE_ANALYSIS = "ASSET_IMAGE_ANALYSIS",
  ASSET_LEXICAL_INDEX = "ASSET_LEXICAL_INDEX",
  ASSET_OCR = "ASSET_OCR",
  ASSET_SCAN = "ASSET_SCAN",
  AUDIT_ARCHIVE = "AUDIT_ARCHIVE",
  AUDIT_ARCHIVE_PURGE = "AUDIT_ARCHIVE_PURGE",
  AUDIT_EXPORT = "AUDIT_EXPORT",
  DATA_EXPORT = "DATA_EXPORT",
  LEXICON_BUILD = "LEXICON_BUILD",
  LEXICON_PUBLISH = "LEXICON_PUBLISH",
  LEXICON_VALIDATE = "LEXICON_VALIDATE",
  RETENTION_PURGE = "RETENTION_PURGE",
  SOURCE_SYNC = "SOURCE_SYNC",
}

export const JOB_KINDS: readonly JobKind[] = Object.freeze(
  Object.values(JobKind),
);

export const isJobKind = (value: unknown): value is JobKind =>
  typeof value === "string" && JOB_KINDS.includes(value as JobKind);
