import { readFile, readdir } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import {
  HarnessError,
  atomicWrite,
  formatJson,
  markdownCell,
  pathExists,
  readJson,
  resolveInside,
  sha256,
  walkFiles,
} from "./common.mjs";
import { CONFIG_RELATIVE_PATH, MANIFEST_RELATIVE_PATH } from "./config.mjs";
import { discoverWorkspace } from "./workspace.mjs";

const GENERATOR_NAME = "@sylis/engineering-harness";
const GENERATOR_VERSION = "0.1.0";
const moduleDirectory = path.dirname(fileURLToPath(import.meta.url));
const assetsRoot = path.resolve(moduleDirectory, "../../assets/default");

async function discoverProject(root, config) {
  const rootPackagePath = resolveInside(root, "package.json");
  const rootPackage = (await pathExists(rootPackagePath))
    ? await readJson(rootPackagePath)
    : {};
  const packages = await discoverWorkspace(root, config.workspace);
  const lockfiles = [
    ["pnpm-lock.yaml", "pnpm"],
    ["yarn.lock", "yarn"],
    ["bun.lock", "bun"],
    ["bun.lockb", "bun"],
    ["package-lock.json", "npm"],
  ];
  let packageManager = rootPackage.packageManager?.split("@")[0] ?? "unknown";
  if (packageManager === "unknown") {
    for (const [lockfile, name] of lockfiles) {
      if (await pathExists(resolveInside(root, lockfile))) {
        packageManager = name;
        break;
      }
    }
  }
  return { rootPackage, packages, packageManager };
}

function renderReferences(content, config) {
  let rendered = content.replaceAll("docs/", `${config.docsRoot}/`);
  for (const [logicalPath, targets] of Object.entries(
    config.documentMappings,
  )) {
    rendered = rendered.replaceAll(
      `${config.docsRoot}/${logicalPath}`,
      targets[0],
    );
  }
  return rendered;
}

function renderTemplate(content, config, discovery) {
  const workspaceRows = discovery.packages.length
    ? discovery.packages
        .map(
          (pkg) =>
            `| \`${markdownCell(pkg.path)}\` | \`${markdownCell(pkg.name ?? "(unnamed)")}\` | ${markdownCell(pkg.group ?? pkg.groups.join(", "))} |`,
        )
        .join("\n")
    : "| `.` | `(no package manifest detected)` | root |";
  const allowedEdges = config.workspace.allowedEdges.length
    ? config.workspace.allowedEdges.map((edge) => `- \`${edge}\``).join("\n")
    : "- No cross-package dependency edges are configured.";
  const replacements = {
    "{{PROJECT_NAME}}": config.project.name,
    "{{DOCS_ROOT}}": config.docsRoot,
    "{{PACKAGE_MANAGER}}": discovery.packageManager,
    "{{WORKSPACE_ROWS}}": workspaceRows,
    "{{ALLOWED_EDGES}}": allowedEdges,
  };
  let rendered = renderReferences(content.replaceAll("\r\n", "\n"), config);
  for (const [token, value] of Object.entries(replacements))
    rendered = rendered.replaceAll(token, value);
  return `${rendered.trimEnd()}\n`;
}

function projectProfile(config, discovery) {
  const rows = discovery.packages.length
    ? discovery.packages
        .map(
          (pkg) =>
            `| \`${markdownCell(pkg.path)}\` | \`${markdownCell(pkg.name ?? "(unnamed)")}\` | ${markdownCell(pkg.group ?? pkg.groups.join(", "))} |`,
        )
        .join("\n")
    : "| `.` | `(unnamed)` | root |";
  return `# Project Profile

Generated by \`${GENERATOR_NAME}\`. Refresh it with the harness init command.

| Property | Value |
| --- | --- |
| Project | ${markdownCell(config.project.name)} |
| Package manager | \`${markdownCell(discovery.packageManager)}\` |
| Documentation root | \`${markdownCell(config.docsRoot)}\` |
| Adoption strategy | \`${markdownCell(config.strategy)}\` |

## Workspace Packages

| Path | Package | Group |
| --- | --- | --- |
${rows}
`;
}

function commandRegistry(discovery) {
  const scripts = Object.entries(discovery.rootPackage.scripts ?? {}).sort(
    ([a], [b]) => a.localeCompare(b),
  );
  const rows = scripts.length
    ? scripts
        .map(
          ([name, command]) =>
            `| \`${markdownCell(name)}\` | \`${markdownCell(command)}\` |`,
        )
        .join("\n")
    : "| `(none)` | No root scripts were detected. |";
  return `# Command Registry

Generated from the target repository's root package manifest. A listed command is discoverable, not automatically proven healthy.

| Script | Command |
| --- | --- |
${rows}

Run the repository's documented install command before invoking commands that require dependencies.
`;
}

function toolCapabilities(config) {
  const rows = config.capabilities.length
    ? config.capabilities
        .map(
          (item) =>
            `| ${markdownCell(item.name)} | ${markdownCell(item.kind)} | ${markdownCell(item.availability)} | ${markdownCell(item.evidence)} |`,
        )
        .join("\n")
    : "| Undiscovered | Unknown | Unknown | Detect capabilities in the active client before relying on them. |";
  return `# Tool Capabilities

This registry records repository-relevant capabilities. Client-specific availability must still be checked in the active session.

| Capability | Kind | Availability | Evidence |
| --- | --- | --- | --- |
${rows}
`;
}

function migrationMap(config) {
  const rows = Object.entries(config.documentMappings).flatMap(
    ([logicalPath, targets]) =>
      targets.map(
        (target) =>
          `| \`${markdownCell(logicalPath)}\` | \`${markdownCell(target)}\` | Reference existing content; do not duplicate it. |`,
      ),
  );
  return `# Harness Migration Map

Generated from \`.harness/config.json\`. Paths on the right remain the source of truth.

| Harness concept | Existing project path | Strategy |
| --- | --- | --- |
${rows.length ? rows.join("\n") : "| `(none)` | `(none)` | No existing documents were mapped. |"}
`;
}

function harnessabilityReport(config, discovery) {
  const mappedConcepts = Object.keys(config.documentMappings).length;
  const namedPackages = discovery.packages.filter((pkg) => pkg.name).length;
  const capabilityCount = config.capabilities.length;
  const gaps = [];
  if (mappedConcepts === 0)
    gaps.push("No existing project documents are mapped into the harness.");
  if (capabilityCount === 0)
    gaps.push("No repository-relevant tool capabilities are recorded.");
  if (namedPackages !== discovery.packages.length)
    gaps.push("At least one workspace package has no name.");
  return `# Harnessability Report

Generated structural assessment for ${markdownCell(config.project.name)}.

| Signal | Value |
| --- | --- |
| Required paths | ${config.requiredPaths.length} |
| Mapped document concepts | ${mappedConcepts} |
| Workspace packages | ${discovery.packages.length} |
| Recorded capabilities | ${capabilityCount} |

## Current Gaps

${gaps.length ? gaps.map((gap) => `- ${gap}`).join("\n") : "- No structural gaps detected by the generator."}

This report measures repository structure only. Passing it does not prove application behavior.
`;
}

function generatedContent(relativeOutput, config, discovery) {
  const generatedRoot = `${config.docsRoot}/generated/`;
  if (!relativeOutput.startsWith(generatedRoot)) return null;
  const name = relativeOutput.slice(generatedRoot.length);
  const generators = {
    "project-profile.md": () => projectProfile(config, discovery),
    "command-registry.md": () => commandRegistry(discovery),
    "tool-capabilities.md": () => toolCapabilities(config),
    "harness-migration-map.md": () => migrationMap(config),
    "harnessability-report.md": () => harnessabilityReport(config, discovery),
  };
  return generators[name]?.() ?? null;
}

function outputForAsset(assetPath, config) {
  if (!assetPath.startsWith("docs/"))
    return { output: assetPath, logicalPath: null };
  const logicalPath = assetPath.slice("docs/".length);
  if (config.documentMappings[logicalPath])
    return { output: null, logicalPath };
  return { output: `${config.docsRoot}/${logicalPath}`, logicalPath };
}

function includeForStrategy(assetPath, strategy) {
  if (strategy === "hybrid") return true;
  return (
    assetPath === "docs/agent-harness.md" ||
    assetPath.startsWith("docs/generated/")
  );
}

async function loadManifest(root) {
  const manifestPath = resolveInside(root, MANIFEST_RELATIVE_PATH);
  if (!(await pathExists(manifestPath))) {
    return {
      schemaVersion: 1,
      generator: { name: GENERATOR_NAME, version: GENERATOR_VERSION },
      files: [],
    };
  }
  const manifest = await readJson(manifestPath);
  if (manifest.schemaVersion !== 1 || !Array.isArray(manifest.files)) {
    throw new HarnessError(
      `Invalid harness manifest: ${MANIFEST_RELATIVE_PATH}`,
    );
  }
  return manifest;
}

export async function initializeHarness({
  root,
  config,
  configRelativePath = CONFIG_RELATIVE_PATH,
  configExists = true,
  dryRun = false,
}) {
  const discovery = await discoverProject(root, config);
  const manifest = await loadManifest(root);
  const previousEntries = new Map(
    manifest.files.map((entry) => [entry.path, entry]),
  );
  const desired = [];

  for (const assetPath of await walkFiles(assetsRoot)) {
    if (!includeForStrategy(assetPath, config.strategy)) continue;
    const { output } = outputForAsset(assetPath, config);
    if (!output) continue;
    const assetContent = await readFile(
      path.join(assetsRoot, assetPath),
      "utf8",
    );
    const generated = generatedContent(output, config, discovery);
    const content =
      generated === null
        ? renderTemplate(assetContent, config, discovery)
        : generated;
    desired.push({
      path: output,
      template: assetPath,
      kind: assetPath.startsWith("docs/generated/") ? "generated" : "scaffold",
      content,
      hash: sha256(content),
    });
  }

  if (!configExists) {
    desired.push({
      path: configRelativePath,
      template: "generated:config",
      kind: "scaffold",
      content: formatJson(config),
      hash: sha256(formatJson(config)),
    });
  }

  const operations = [];
  const nextEntries = new Map(previousEntries);
  for (const item of desired.sort((a, b) => a.path.localeCompare(b.path))) {
    const absolute = resolveInside(root, item.path);
    const exists = await pathExists(absolute);
    const previous = previousEntries.get(item.path);
    if (!exists) {
      operations.push({ action: "create", ...item });
      nextEntries.set(item.path, {
        path: item.path,
        kind: item.kind,
        template: item.template,
        hash: item.hash,
      });
      continue;
    }

    const currentContent = await readFile(absolute, "utf8");
    const currentHash = sha256(currentContent);
    if (!previous) {
      operations.push({
        action: "skip",
        reason: "existing file is not generator-owned",
        ...item,
      });
      continue;
    }
    if (item.kind === "scaffold") {
      operations.push({
        action: "skip",
        reason: "scaffold files are user-owned after creation",
        ...item,
      });
      continue;
    }
    if (currentHash !== previous.hash) {
      operations.push({
        action: "conflict",
        reason: "generated file changed outside the generator",
        ...item,
      });
      continue;
    }
    if (currentHash === item.hash) {
      operations.push({ action: "skip", reason: "unchanged", ...item });
      nextEntries.set(item.path, {
        path: item.path,
        kind: item.kind,
        template: item.template,
        hash: item.hash,
      });
      continue;
    }
    operations.push({ action: "update", ...item });
    nextEntries.set(item.path, {
      path: item.path,
      kind: item.kind,
      template: item.template,
      hash: item.hash,
    });
  }

  const conflicts = operations.filter(
    (operation) => operation.action === "conflict",
  );
  if (conflicts.length > 0) {
    return { operations, conflicts, discovery, wrote: false };
  }

  const nextManifest = {
    schemaVersion: 1,
    generator: { name: GENERATOR_NAME, version: GENERATOR_VERSION },
    files: [...nextEntries.values()].sort((a, b) =>
      a.path.localeCompare(b.path),
    ),
  };
  const manifestContent = formatJson(nextManifest);
  const manifestExists = await pathExists(
    resolveInside(root, MANIFEST_RELATIVE_PATH),
  );
  const currentManifestContent = manifestExists
    ? await readFile(resolveInside(root, MANIFEST_RELATIVE_PATH), "utf8")
    : null;
  if (currentManifestContent !== manifestContent) {
    operations.push({
      action: manifestExists ? "update" : "create",
      path: MANIFEST_RELATIVE_PATH,
      content: manifestContent,
      kind: "generated",
      template: "generated:manifest",
      hash: sha256(manifestContent),
    });
  }

  if (!dryRun) {
    for (const operation of operations) {
      if (operation.action === "create" || operation.action === "update") {
        await atomicWrite(root, operation.path, operation.content);
      }
    }
  }
  return { operations, conflicts: [], discovery, wrote: !dryRun };
}

export async function targetHasProjectContent(root) {
  const entries = await readdir(root);
  return entries.some((entry) => !new Set([".git", ".harness"]).has(entry));
}
