export enum LexiconPublishProgressStage {
  BUILDING_RELEASE = "BUILDING_RELEASE",
  MATERIALIZING = "MATERIALIZING",
  PREFLIGHT_COMPLETE = "PREFLIGHT_COMPLETE",
  RELEASE_BUILT = "RELEASE_BUILT",
  STAGING = "STAGING",
  STAGING_COMPLETE = "STAGING_COMPLETE",
  VALIDATED = "VALIDATED",
  VALIDATING_RELEASE = "VALIDATING_RELEASE",
}

export enum LexiconPublishResultType {
  RELEASE = "LEXICON_RELEASE",
  RELEASE_VALIDATION = "LEXICON_RELEASE_VALIDATION",
}
