export const ARTIFACT_ROLES = ["CURRENT", "LINEAGE_ANCHOR"] as const;
export const ENTRY_TYPES = ["WORD", "MULTIWORD", "AFFIX"] as const;
export const FORM_TYPES = [
  "CANONICAL",
  "INFLECTED",
  "VARIANT",
  "ABBREVIATED",
] as const;
export const PEDAGOGICAL_MATERIAL_KINDS = [
  "LEARNER_EXPLANATION",
  "MORPHOLOGY_WALKTHROUGH",
  "CULTURAL_CONTEXT",
  "MNEMONIC",
  "MICRO_STORY",
] as const;
export const EXERCISE_TASK_KINDS = [
  "FORM_MEANING_MAPPING",
  "SPOKEN_FORM_MAPPING",
  "SPOKEN_FORM_PRODUCTION",
  "CONTEXTUAL_SENSE_INTERPRETATION",
  "CONTEXTUAL_FORM_COMPLETION",
  "COLLOCATION_RECALL",
  "FRAME_COMPLETION",
  "SEMANTIC_RELATION_DISCRIMINATION",
  "MORPHEME_ANALYSIS",
  "WORD_FORMATION",
  "USAGE_CONSTRAINT_DISCRIMINATION",
  "SENTENCE_TRANSLATION",
  "SENTENCE_PRODUCTION",
] as const;
export const KNOWLEDGE_FACETS = [
  "FORM_SPOKEN",
  "FORM_WRITTEN",
  "FORM_WORD_PARTS",
  "MEANING_FORM_MEANING",
  "MEANING_CONCEPT_REFERENT",
  "MEANING_ASSOCIATIONS",
  "USE_GRAMMATICAL_FUNCTION",
  "USE_COLLOCATION",
  "USE_CONSTRAINTS",
] as const;
export const EVIDENCE_KINDS = [
  "RECOGNITION",
  "CUED_RECALL",
  "CONTEXTUAL_DISCRIMINATION",
  "CONSTRAINED_PRODUCTION",
  "FREE_PRODUCTION",
] as const;

export type ArtifactRole = (typeof ARTIFACT_ROLES)[number];
export type EntryType = (typeof ENTRY_TYPES)[number];
export type FormType = (typeof FORM_TYPES)[number];
export type PedagogicalMaterialKindCode =
  (typeof PEDAGOGICAL_MATERIAL_KINDS)[number];
export type ExerciseTaskKind = (typeof EXERCISE_TASK_KINDS)[number];
export type KnowledgeFacet = (typeof KNOWLEDGE_FACETS)[number];
export type EvidenceKind = (typeof EVIDENCE_KINDS)[number];
